title: Deep Learning Security Workshop
tagline: February 19-20, 2017
email: deep-learning-security@googlegroups.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://deep-learning-security.github.io" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
